# Generated by Django 3.1.3 on 2020-11-11 14:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20201104_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
